<?php if ($this->isPossibleSinglepageCheckout()):?>
    <button
        type="button"
        title="<?php echo $this->__('Checkout in Single Page') ?>"
        class="button btn-proceed-checkout btn-checkout<?php
        if ($this->isDisabled()):
            ?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php
        endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';">
        <span><span><?php echo $this->__('Checkout in Single Page') ?></span></span></button>
<?php endif?>
